apiVersion: v1
kind: Service
metadata:
  namespace: search-environment
  name: search-webapi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: search-webapi
  type: LoadBalancer
