apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search-environment
  name: search-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-webapi
  template:
    metadata:
      labels:
        app: search-webapi
    spec:
      containers:
        - name: search-webapi
          image: localhost:5000/search-webapi:1.4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: search-environment
  name: search-webapi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: search-webapi
  type: ClusterIP
