apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend-environment
  name: bookstore-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
      - name: bookstore-frontend
        image: cloudcompdocker/bookstore-frontend:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]