apiVersion: v1
kind: Service
metadata:
  namespace: frontend-environment
  name: bookstore-frontend
  labels:
    app: bookstore-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bookstore-frontend
  type: LoadBalancer
  
