# tomcat
apiVersion: v1
kind: Service
metadata:
  namespace: shoppingcart-environment
  name: tomcat-shoppingcart
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomcat-shoppingcart
  type: LoadBalancer
  ---
  # mysql
  apiVersion: v1
  kind: Service
  metadata:
    namespace: shoppingcart-environment
    name: mysql-shoppingcart
  spec:
    ports:
      - port: 3306
        targetPort: 3306
    selector:
      app: tomcat-shoppingcart
    type: ClusterIP
