apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingcart-environment
  name: shoppingcart-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-shoppingcart
  template:
    metadata:
      labels:
        app: tomcat-shoppingcart
    spec:
      containers:
        - name: tomcat-shoppingcart
          image: localhost:5000/tomcat-shoppingcart:1.0
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  namespace: shoppingcart-environment
  name: tomcat-shoppingcart
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: tomcat-shoppingcart
  type: ClusterIP