name: frontend_CICD

on:
  push:
    paths:
    - 'frontend-bookstore/**'

defaults:
  run:
    working-directory: ./frontend-bookstore/bookstore

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudcompdocker
          password: CloudCompPwd
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: cloudcompdocker/bookstore-frontend:latest
