name: search_CICD

on:
  push:
    paths:
     - 'microservice-search/**'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cloudcompdocker
          password: CloudCompPwd
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./microservice-search/webapi/BookStoreSearch/
          file: BookStoreSearch/Dockerfile
          push: true
          tags: cloudcompdocker/search-webapi:latest
