name: search_CICD

on:
  workflow_dispatch:
  push:
    paths:
     - 'microservice-search/**'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./microservice-search/webapi/BookStoreSearch/
          file: microservice-search/webapi/BookStoreSearch/BookStoreSearch/Dockerfile
          push: true
          tags: cloudcompdocker/search-webapi:latest
      - 
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GK_KEY }}
          project_id: ${{ secrets.GK_PROJECT_ID }}
      - 
        run: |-
          gcloud container clusters get-credentials "cluster-1" --zone "us-central1-c"
      - 
        name: Update Deployment and Services
        run: |-
          kubectl apply -f ./microservice-search/namespace.yaml
          kubectl apply -f https://download.elastic.co/downloads/eck/1.3.0/all-in-one.yaml
          kubectl apply -f ./microservice-search/elasticsearch.yaml
          kubectl apply -f ./microservice-search/service.yaml
      - 
        name: Deploy
        run: |-
          kubectl rollout -f ./microservice-search/deployment.yaml --namespace search-environment
